<a href="https://colab.research.google.com/github/zachuragi/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Lacuesta_Ituriaga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TASK 1
Create a function named mat_desc() that througouhly describes a matrix, it should:


*   Displays the shape, size, and rank of the matrix.
*   Displays whether the matrix is square or non-square.
*   Displays whether the matrix is an empty matrix.
*   Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
# mat_desc function 

def mat_desc(mat):
  sq = False                                                  # initial value, to be replaced depending on conditions
  mat = np.array(mat)

  print(mat)
  print('\n' + 'Shape:', mat.shape)
  print('Size:', mat.size)
  print('Rank:', np.linalg.matrix_rank(mat))

  if(mat.shape[0] == mat.shape[1]):
    sq = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
    
  if(mat.shape[0] == 0 and mat.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix is not empty')

  iden = np.identity(mat.shape[0])
  one = np.ones(mat.shape[0], dtype=int)

  if sq == True :                                           # executed only if the matrix is square 
    if  sq and (iden== mat).all():
      print('Identity Matrix')
    elif (one == mat).all() :
      print('Ones matrix')
    elif (one != mat).all():
      print('Zeros Matrix')
    else:
      print()
  
  one_not_square = np.ones((mat.shape[0], mat.shape[1]))    # basis for either ones or zeros matrices that are non-square
  zeros_not_square = np.zeros((mat.shape[0], mat.shape[1]))

  if sq == False :
    if (one_not_square == mat).all() :
      print('Ones matrix')
    elif (zeros_not_square != mat).all():
      print('Zeros Matrix')
    else:
      print()

In [ ]:
mat_desc([
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]
])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Shape: (3, 4)
Size: 12
Rank: 0
Non-Square Matrix
Matrix is not empty



In [ ]:
mat_desc([
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]
])

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape: (4, 4)
Size: 16
Rank: 1
Square Matrix
Matrix is not empty
Ones matrix


In [ ]:
mat_desc([
          [1, 0, 0, 0],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
])

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Shape: (4, 4)
Size: 16
Rank: 4
Square Matrix
Matrix is not empty
Identity Matrix


In [ ]:
mat_desc([
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]
])

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Shape: (5, 5)
Size: 25
Rank: 0
Square Matrix
Matrix is not empty
Zeros Matrix


In [ ]:
mat_desc([
          [2, 4, 6, 8],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]
])

[[2 4 6 8]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Shape: (5, 4)
Size: 20
Rank: 1
Non-Square Matrix
Matrix is not empty



#TASK 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

*   Determines if the matrices are viable for operation and returns your own error message if they are not viable.
*   Returns the sum of the matrices.
*   Returns the difference of the matrices.
*   Returns the element-wise multiplication of the matrices.
*   Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('Shape of Both Matrices are Not the Same. Sorry we cannot perform the operations.')
        return
    print('Sum of the Given Matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the Given Matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-Wise Multiplication of the Given Matrices:')
    mmul = np.multiply(mat1, mat2)
    print(mmul)
    print('Element-Wise Division of the Given Matrices:')
    mmul = np.divide(mat1, mat2)
    print(mmul)

In [ ]:
mat_operations([[2, 4, 6], [1, 2, 3], [3, 2, 1]], 
               [[0, 1, 0], [1, 1, 1], [0, 0, 0]])

Matrix 1: [[2 4 6]
 [1 2 3]
 [3 2 1]]
Matrix 2: [[0 1 0]
 [1 1 1]
 [0 0 0]]
Sum of the Given Matrices:
[[2 5 6]
 [2 3 4]
 [3 2 1]]
Difference of the Given Matrices:
[[2 3 6]
 [0 1 2]
 [3 2 1]]
Element-Wise Multiplication of the Given Matrices:
[[0 4 0]
 [1 2 3]
 [0 0 0]]
Element-Wise Division of the Given Matrices:
[[inf  4. inf]
 [ 1.  2.  3.]
 [inf inf inf]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


In [ ]:
mat_operations([[2, 0, 0], [0, 2, 0], [0, 0, 2]],
               [[1, 2, 4], [2, 3, 4], [4, 5, 6]])

Matrix 1: [[2 0 0]
 [0 2 0]
 [0 0 2]]
Matrix 2: [[1 2 4]
 [2 3 4]
 [4 5 6]]
Sum of the Given Matrices:
[[3 2 4]
 [2 5 4]
 [4 5 8]]
Difference of the Given Matrices:
[[ 1 -2 -4]
 [-2 -1 -4]
 [-4 -5 -4]]
Element-Wise Multiplication of the Given Matrices:
[[ 2  0  0]
 [ 0  6  0]
 [ 0  0 12]]
Element-Wise Division of the Given Matrices:
[[2.         0.         0.        ]
 [0.         0.66666667 0.        ]
 [0.         0.         0.33333333]]


In [ ]:
mat_operations([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[-1, -2, -3], [-4, -5, -6], [-6, -8, -9]])

Matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: [[-1 -2 -3]
 [-4 -5 -6]
 [-6 -8 -9]]
Sum of the Given Matrices:
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Difference of the Given Matrices:
[[ 2  4  6]
 [ 8 10 12]
 [13 16 18]]
Element-Wise Multiplication of the Given Matrices:
[[ -1  -4  -9]
 [-16 -25 -36]
 [-42 -64 -81]]
Element-Wise Division of the Given Matrices:
[[-1.         -1.         -1.        ]
 [-1.         -1.         -1.        ]
 [-1.16666667 -1.         -1.        ]]


In [ ]:
mat_operations([[1, 1, 1], [3, 3, 3], [5, 5, 5]],
               [[0, 0, 0], [2, 2, 2], [4, 4, 4]])

Matrix 1: [[1 1 1]
 [3 3 3]
 [5 5 5]]
Matrix 2: [[0 0 0]
 [2 2 2]
 [4 4 4]]
Sum of the Given Matrices:
[[1 1 1]
 [5 5 5]
 [9 9 9]]
Difference of the Given Matrices:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Element-Wise Multiplication of the Given Matrices:
[[ 0  0  0]
 [ 6  6  6]
 [20 20 20]]
Element-Wise Division of the Given Matrices:
[[ inf  inf  inf]
 [1.5  1.5  1.5 ]
 [1.25 1.25 1.25]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


In [ ]:
mat_operations([[0, 0, 0], [0, 0, 0], [0, 0, 0]], 
               [[0, 0, 0], [0, 0, 0], [0, 0, 0]])

Matrix 1: [[0 0 0]
 [0 0 0]
 [0 0 0]]
Matrix 2: [[0 0 0]
 [0 0 0]
 [0 0 0]]
Sum of the Given Matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Difference of the Given Matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-Wise Multiplication of the Given Matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-Wise Division of the Given Matrices:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide
